"""
Export builder — generates JSON and Markdown documentation artifacts.
"""
from datetime import datetime
from models.documentation import DocumentationArtifact


def build_json(artifact: DocumentationArtifact, profile=None) -> dict:
    """Build the JSON export payload for a table."""
    return {
        "table_name": artifact.table_name,
        "fully_qualified_name": artifact.fully_qualified_name,
        "generated_at": artifact.generated_at.isoformat(),
        "model_used": artifact.model_used,
        "business_summary": artifact.business_summary,
        "usage_recommendations": artifact.usage_recommendations,
        "quality_score": artifact.quality_score,
        "quality_profile": {
            "row_count": profile.row_count if profile else None,
            "overall_completeness_pct": profile.overall_completeness_pct if profile else None,
            "grade": profile.grade if profile else None,
            "freshness_timestamp": profile.freshness_timestamp.isoformat() if (profile and profile.freshness_timestamp) else None,
        } if profile else {},
        "columns": [
            {
                **col,
                "quality": (
                    pcol.dict()
                    if (pcol := next((pc for pc in profile.columns if pc.column_name == col.get("name") or pc.column_name == col.get("column_name")), None))
                    else {}
                )
            }
            for col in artifact.columns
        ] if profile else artifact.columns,
    }


def build_markdown(artifact: DocumentationArtifact, profile=None) -> str:
    """Build a GitHub-renderable Markdown documentation artifact."""
    ts = artifact.generated_at.strftime("%Y-%m-%d %H:%M UTC")
    score = artifact.quality_score

    # Quality badge
    if score >= 90:   badge = "🟢"
    elif score >= 70: badge = "🟡"
    else:             badge = "🔴"

    lines = [
        f"# {artifact.table_name}",
        "",
        f"> **Documentation generated by Turgon** | {ts} | Model: `{artifact.model_used}`",
        "",
        "---",
        "",
        "## 📋 Business Summary",
        "",
        artifact.business_summary,
        "",
        "---",
        "",
        "## 💡 Usage Recommendations",
        "",
        artifact.usage_recommendations,
        "",
        "---",
        "",
        "## 📊 Data Quality",
        "",
        f"| Metric | Value |",
        f"|---|---|",
        f"| Overall Score | {badge} **{score}/100** |",
    ]

    if profile:
        lines += [
            f"| Completeness | {profile.overall_completeness_pct}% |",
            f"| Grade | {profile.grade} |",
            f"| Row Count | {profile.row_count:,} |",
            f"| Freshness | {profile.freshness_timestamp.strftime('%Y-%m-%d %H:%M UTC') if profile.freshness_timestamp else 'Unknown'} |",
        ]

    lines += ["", "---", "", "## 🗂️ Schema", "", "| Column | Type | Completeness | Distinctness | Description |", "|---|---|---|---|---|"]

    for col in artifact.columns:
        pcol = next((pc for pc in profile.columns if pc.column_name == col.get("name") or pc.column_name == col.get("column_name")), None) if profile else None
        
        comp = f"{pcol.completeness_pct}%" if pcol else "—"
        dist = f"{pcol.distinctness_pct}%" if pcol else "—"
        
        lines.append(
            f"| `{col.get('name') or col.get('column_name', '')}` | `{col.get('data_type', '')}` "
            f"| {comp} | {dist} | {col.get('ai_description') or col.get('description', '—')} |"
        )

    lines += ["", "---", "", f"*Generated by [Turgon](https://github.com/turgon) on {ts}*"]
    return "\n".join(lines)
